authors        = ["Osman Mesut Ozcan <panikka.studio>", "ask4fusora <ask4fusora@gmail.com>"]
description    = "Dprint support for Zed"
id             = "dprint"
name           = "Dprint"
repository     = "https://github.com/panikkastudio/dprint-zed"
schema_version = 1
version        = "0.1.0"

[language_servers.dprint]
name = "dprint"
languages = [
  "JavaScript",
  "TypeScript",
  "TSX",
  "JSON",
  "JSONC",
  "Markdown",
  "TOML",
  "CSS",
  "SCSS",
  "LESS",
  "HTML",
  "Vue.js",
  "Svelte",
  "Astro",
  "Angular",
  "Twig",
  "GraphQL",
  "YAML",
  "PHP",
  "Python"
]
