authors        = ["Osman Mesut Ozcan <panikka.studio>"]
description    = "Dprint support for Zed"
id             = "dprint"
name           = "Dprint"
repository     = "https://github.com/dprint/dprint"
schema_version = 1
version        = "0.0.1"

[language_servers.dprint]
name = "Dprint Language Server"
code_action_kinds = ["quickfix"]
language = "JavaScript"
languages = [
  "JavaScript",
  "JSX",
  "TypeScript",
  "TSX",
  "Vue.js",
  "Astro",
  "Svelte",
  "JSON",
  "JSONC",
  "CSS",
  "GraphQL",
  "HTML",
]

[language_servers.dprint.language_ids]
"Astro"      = "astro"
"CSS"        = "css"
"GraphQL"    = "graphql"
"HTML"       = "html"
"JSON"       = "json"
"JSONC"      = "jsonc"
"JSX"        = "javascriptreact"
"JavaScript" = "javascript"
"Svelte"     = "svelte"
"TSX"        = "typescriptreact"
"TypeScript" = "typescript"
"Vue.js"     = "vuejs"
